name: Devops-Practice-1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # run a single command using the runner shell
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 24.19.0 
    # run a set of command using the runner shell
    - name: Installing surge
      run: npm install --global surge
    - name: deploying using surge
      run: surge ./ devops-Practice-1.surge.sh --token ${{secrets.Devops-Practice-1}} 
